### ISSUE TITLE
broken IIf

### ISSUE THREAD

**Issue by Mumpitz** [Mumpitz/KudzuASP#1]
In Line 832 of _kudzu.asp, the IIf Handler is set to Class `CTPSubst` What would need to be `CTPIIf`.
And then the Class `CTPIIf` itself has a logical failure.
If the expression evaluates to false, `Exit Sub` is triggered, instead of returning the third parameter.
Removing the Condition would be correct, right?

**Comment by TriLogic** [comment]
You are correct on the change to CTPIIf.  I'll look into the IIF logic
error.
