### ISSUE TITLE
Which is the correct code?

### ISSUE THREAD

**Issue by Mumpitz** [Mumpitz/KudzuASP#3]
I found Sourcecode at your website http://www.andrewfriedl.com/ that has the Version Number 1.2.5 and seems to be a bit more advanced then the version 1.6.0 here in the repo.

At least there is a Class `CTPRandom` and Class `CTemplateNode` has the additional Properties `mIncluded`, `Get Included` and `Set IncludeNode`.
The Sub EvalNodeID changed to a Function and there are minifications to save some lines of code.

In 1.2.5's `CTemplatenEngine::WriteOutput(sContent)` is `ENGINE` not present as well as the Condition `If Not mParent is Nothing Then` in `CTemplateEngine::ContentFlush()`.
Are these missing by mistake?

The Line with libPathPush at the beginning was removed in 1.6.0?

Seems to be quite mixed up a bit. Would like to bring some light into the dark. ;)

**Comment by TriLogic** [comment]
I will need to bring down both sets of source and perform a diff on them.
I had someone else also working on the code and things got a little
confused.  I'd like to resolve them myself but my time is at a premium
these days.

Andrew

**Comment by Mumpitz** [comment]
Having that Project on Github is an improvement i think.

Currently i am trying to understand the the Engine and how it works.
I also work on expanding it already.

**Comment by lynx12345** [comment]
Hi, this is the only template asp library that seems to work ok; but I can´t make it work with any of the examples out there.... Can any put a code example thats works? with this github version? thnks in advance!

**Comment by Mumpitz** [comment]
Hi @lynx12345, i've created a new issue for questions like that. #6 
Since i have currently no Documentation that i could send or link you, i've created two simple Gists with an ASP and HTML-Template.

https://gist.github.com/Mumpitz/8f3abea0fdf83104c35e7fbe2114110d
https://gist.github.com/Mumpitz/d0310ad7d8b3c855ac235d3b807f65b2

I hope they will help you. If you need more specific help, please use #6 to ask.

Since the original question has been answered meanwhile, i will close this issue.
