### ISSUE TITLE
broken explicit VBScript Eval {{!}}

### ISSUE THREAD

**Issue by Mumpitz** [Mumpitz/KudzuASP#4]
The exclamation mark is not filtered out, so the eval will always fail.

I will fix it and create another Pull-Request.

**Comment by TriLogic** [comment]
I have performed a merge of the Github code to my personal code base which
included a change someone else wanted and added.

I will zip up the code and send it directly to you and you can perform the
merging.

How would you like to be the owner of this project?  I do not have time to
support it any longer.

Thanks,
Andrew

**Comment by Mumpitz** [comment]
It would be an honor to take over the project. I would like to do that.

Instead of zipping the code, you could simply add a new branch to the repository.

**Comment by TriLogic** [comment]
Ok.  I'll send you the code that I have and the demo website I started that
goes with it.  I'll let you manage the repository.  Do you need me to do
anything to transfer the project?

Thanks,
Andrew

**Comment by Mumpitz** [comment]
After you added your code and demo stuff in a new branch, you could go to the github repository settings and transfer the ownership to me. [Transferring a repository - User Documentation](https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts)
So i would be able to manage pull requests, issues, milestones, etc.

**Comment by TriLogic** [comment]
Ok,

Here is the the latest set of code from my systems.  You will need to
compare it to your changes. Consider the project to be yours going
forward.  Please leave my name in the source code as I believe I should be
credited with the original code.

I will transfer the project over to you today.

Thanks,
Andrew
