### ISSUE TITLE
it is not working correctly

### ISSUE THREAD

**Issue by mbnl** [Mumpitz/KudzuASP#8]
T_ENGINE.PathPrefix .... Error

**Comment by mbnl** [comment]
Microsoft VBScript runtime error '800a01b6'

Object doesn't support this property or method: 'PathPrefix'

/kudzu/kudzu_demo.asp, line 12

**Comment by bawalker2019** [comment]
Did you ever get a resolution to this - I am getting the same error - its a shame, kudzuASP used to have a great reputation, but its useless if we can't get it to work anymore..

**Comment by tomascarlo** [comment]
I used it without pathPrefix, just importing _kudzu.asp.
Yet I am not able to use the "iterate" library, though.

**Comment by TriLogic** [comment]
> I used it without pathPrefix, just importing _kudzu.asp.
> Yet I am not able to use the "iterate" library, though.

If you look at the Github repository you can see that the stock iterators have been moved to their own library.  You need to load the iteration components to use them.

As the original author of KudzuASP I stopped using stock iterators in favor of writing custom components which is easier and much more reliable.

**Comment by Mumpitz** [comment]
This should fix missing PathPrefix Issue and make the Gists a valid example.

As for the Iterators, i'll add our Inhouse Library to the Repo soon as mentioned in #7 
As well as updating the Examples with that commit.
